### ISSUE TITLE
Make a claw subsystem

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#1]
**Summary**
This year, we plan on having a claw to manipulate the game elements. The claw shall consist of a single servo and a digital IR sensor pointing outwards from the pivot of the claw (basically, it gets triggered if anything is in the claw). The claw needs to have a function that sets the servo to a given position. There are going to be three main positions: default (open), closed (traffic cone), closed (cube). Add them to paramters.toml, as well as shuffleboard (in the subsystem). Also add a Reset() function, although this doesn't need to do anything for now.

**Work Required**
 - create subsystem class
 - add servo to Actuators interface
 - add digital IR sensor to Actuators interface
 - add functions to Claw subsystem
 - add values to parameters.toml
 - add shuffleboard to the Claw subsystem

**Verification**
 - CI passes
 - claw subsystem has above mentioned functionality

**Comment by X-EX3-X** [comment]
how

**Comment by X-EX3-X** [comment]
note to self:
work on claw next time

**Comment by jkleiber** [comment]
This was done in#37
