### ISSUE TITLE
Add joysticks and buttons

### ISSUE THREAD

**Issue by jkleiber** [Team-OKC-Robotics/FRC-2023#12]
**Summary**
There need to be joysticks and buttons declared in RobotContainer.h and initialized in RobotContainer.cpp

**Work to Do**
- Add Joysticks and JoystickButtons in RobotContainer.h
- Initialize Joysticks/Buttons in RobotContainer.cpp in an initialization function

**Verification**
- Joysticks and buttons are added correctly to RobotContainer

**Deferred Work**
- Each subsystem should add button bindings appropriately as part of their work

**Comment by jkleiber** [comment]
@AbbeySieg since you're already sort of working on this, I'm assigning it to you

**Comment by AbbeySieg** [comment]
@jkleiber  I think I did it, but I'm not sure

**Comment by danielbrownmsm** [comment]
what branch was this on? I thought @AbbeySieg finished it, but I could be misremembering things

**Comment by jkleiber** [comment]
This work has been done as part of the hardware branch and is now on master. We can close this
