### ISSUE TITLE
Shuffleboard only shows whole numbers for floating point values

### ISSUE THREAD

**Issue by jkleiber** [Team-OKC-Robotics/FRC-2023#13]
**Summary**
Shuffleboard is only showing whole numbers when it should be showing floating point values. For example `3.14159` would show up as `3`. We need to figure out why, and fix it.

**Work**
- Make shuffleboard show the decimal places for floating point values

**Verification**
- Shuffleboard shows the decimal places

**Comment by danielbrownmsm** [comment]
I figured it out. In UserInterface.cpp the entries were being created and given initial values of 0, which initialized the entries to have type int. Changed those to 0.0, and everything worked fine after that (this is all on FRC-2022-CPP)

**Comment by jkleiber** [comment]
Good find. I think we can justify closing this then
