### ISSUE TITLE
Create Hardware interface

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#2]
**Summary**
The hardware interface (and component actuator and sensor interfaces) from the beta test code was a really convenient thing to have, with all of our hardware defined in one go in a centrally located space. I believe we should have something similar this year, although maybe somewhat more monolithic. I'm not entirely sure how many layers of pointers we will have, but for now just copying what we had in the beta reop should be sufficient for now.

**Work Required**
 - copy beta code over to this repo for the HardwareInterface, ActuatorInterface, and SensorInterface
 - add the hardware interface code into RobotContainer

**Verification**
 - CI passes
 - code is not spaghetti, or at least it's well-documented spaghetti

**Comment by danielbrownmsm** [comment]
go ahead and add in all expected hardware for the planned design:
 - 8 swerve drive motors
 - 4 absolute steer encoders
 - 4 drive REV RelativeEncoder (the built-in ones)
 - 2 lift motors
 - 2 lift REV RelativeEncoder (the built-in ones) - 2 arm motors
 - 2 arm motors
 - 2 arm REV RelativeEncoder (the built-in ones)
 - 1 claw servo
 - 1 digital IR claw sensor
 - 1 PhotonVision camera

**Comment by danielbrownmsm** [comment]
scratch making a separate class

**Comment by danielbrownmsm** [comment]
okay nevermind it's probably fixed but also having everything separate from RobotContainer is still a little bit of a pain

**Comment by AbbeySieg** [comment]
@jkleiber what do I need to copy and paste from the swerve drive code

**Comment by jkleiber** [comment]
@AbbeySieg start with the SwerveDriveHardwareInterface and the swerve drive motors in the HardwareInterface code

**Comment by AbbeySieg** [comment]
@jkleiber I can't find the code.

**Comment by jkleiber** [comment]
Done in #9
