### ISSUE TITLE
Create Arm/Lift subsystem

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#3]
**Summary**
The current robot design includes an extending arm combo. The arm will most likely have two motors on it facing each other. There will be another motor to extend the arm. These will all be brushless motors and have encoders. The subsystem needs to have a couple of functions:
 - a function to set the desired horizontal extension of the lift, in inches
 - a function to set the desired angle of the arm
 - a function to get the desired displacement
 - a function to get the desired angle
In periodic, the subsystem shall update shuffleboard and motor outputs to achieve the desired state, using PID controllers. As this is just the base level of code, and the design is very subject to change, the code does not necessarily need to work, but it does need to build.

**Work Required**
 - create subsystem
 - add actuators
 - create functions
 - add shuffleboard stuff
 - write Periodic()

**Verification**
 - CI passes
 - code is documented

**Comment by danielbrownmsm** [comment]
okay, so design changed design and now we extend the arm, no lift

**Comment by jkleiber** [comment]
This is now done as of #36
