### ISSUE TITLE
Delete all of the "example" template code

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#5]
Ticket Template
**Summary**
When you make a new project, WPILib starts you off with some example code that you never end up using, to create a template for you. We aren't going to use it, so delete it. This is a good issue to practice our software development process with. Also, we don't need the constants file, as we shall be using TOML to store all of our robot constants.

**Work Required**
 - remove "ExampleSubsystem.h"
 - remove "ExampleSubsystem.cpp"
 - remove "ExampleCommand.h"
 - remove "ExampleCommand.cpp"
 - remove "Constants.h"
 - fix RobotContainer so the code builds

**Verification**
 - all example files removed
 - CI passes

**Comment by deadlyvortex** [comment]
examplecommand cpp done
examplecommand.h
examplesubsystem cpp
example subsytem.h
constants.h
robot container
all done
