### ISSUE TITLE
Intake Improvements

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#65]
**Summary**
Some miscellaneous improvements we can make to the intake before GKC.

**Work Required**
 - put tilt setpoint on shuffleboard
 - make spitting stuff out of the intake faster
 - tune wrist tilt

**Verification**
 - CI passes

**Comment by jkleiber** [comment]
@danielbrownmsm is this complete?

**Comment by danielbrownmsm** [comment]
I think so yeah. The tilt sensor/setpoint is on shuffleboard, we upped the power of the intake and it kind of got tuned. Of course, better setpoints are on feat/GKC but yeah.
