### ISSUE TITLE
Make the arm not oscillate around 0

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#66]
**Summary**
Whenever the arm is trying to PID to 0, the tension on the chain will swap from one side to the other of the sprocket as the arm swings around, which starts it oscillating as the arm is basically a pendulum. If we could simply not apply power to the arm if the setpoint is 0 and the error is small (probably only 5-10 degrees) then we can save a lot of wear and tear on the robot and make driving easier.

**Work Required**
 - make the arm not oscillate around 0

**Verification**
 - CI passes

**Comment by jkleiber** [comment]
@danielbrownmsm did this get resolved by the scoring integration branch?

**Comment by danielbrownmsm** [comment]
yes
