### ISSUE TITLE
Arm Improvements

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#71]
**Summary**
It's that time of year again, and the arm needs to be improved for worlds.

**Work Required**
 - make the arm commands blocking (only return true in isFinished() if the arm is at the setpoint)
 - add acceleration limits to the extend
 - add acceleration limits to the raise/lower
 - add the manual control back in, just in case
 - add a button on shuffleboard to activate/deactivate manual control

**Verification**
 - CI passes
 - code is not bad

**Comment by AbbeySieg** [comment]
This was done on feat/GKC

**Comment by danielbrownmsm** [comment]
everything except acceleration limits, but those can be deferred to another issue
