### ISSUE TITLE
Remove old new intake code

### ISSUE THREAD

**Issue by danielbrownmsm** [Team-OKC-Robotics/FRC-2023#77]
**Summary**
We had the new intake design with the wrist for cubes and cones. Which broke at Kansas City, and we don't really have a replacement lined up, so we're just putting the old intake back on slightly modified. Which means we don't need all the new intake with the wrist code anymore, so we should remove it.

**Work Required**
 - remove all code related to the wrist intake

**Verification**
 - CI passes
 - no trace left of the wrist intake cod

**Comment by X-EX3-X** [comment]
I DID IT
